#!/usr/bin/env python3
"""Fab setup for the ESP32-S3 4-20 mA board: stackup, netclasses and JLCPCB's
design rules. Run whenever the netlist changes, and always before routing:

    "C:\\Program Files\\KiCad\\10.0\\bin\\python.exe" setup_fab.py

Idempotent. It writes three things and moves nothing:
  * the stackup into the .kicad_pcb (JLCPCB 2-layer 1.6 mm, "JLC0216A"),
  * netclasses + board constraints into the .kicad_pro,
  * <project>.kicad_dru -- the JLCPCB rules KiCad's constraint table cannot
    express (KiCad loads that file by name, no import step).

Rule values are JLCPCB's no-surcharge tier with margin, read from their
capabilities pages on 2026-09-20 for the USB-C / M.2 adapter and reused here:
0.3 mm via holes, 0.127 mm track/space (limit 0.10), 0.3 mm copper to a
routed edge (limit 0.2).

Netclasses, and why each exists:
  USB     the ESP32-S3's native USB is FULL speed (12 Mbit/s), so impedance
          is not critical over 40 mm. The pair is still routed coupled, at
          0.25 / 0.20 mm, over unbroken bottom ground wherever it can be.
  POWER   +5V, VIN_SW, +3V3, +24V and the boost switch node. 0.4 mm is the
          width the autorouter uses for branches; the trunks and the boost
          loop are scripted wider in route_board.py.
  LOOP    the 24 V field loop. 35 mA at most, so width is not the point:
          0.25 mm clearance is, because these nets see the surge that the
          SMAJ28A clamps at about 45 V.
  GND     its own class so the autorouter can be told to leave it alone
          (-inc GND): ground is pours and scripted vias, never a thin
          autorouted trace.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pcblib                       # noqa: E402
from pcblib import Board, say       # noqa: E402

NAME = "esp32-4to20ma-board"
W, H = 40.0, 61.0

STACKUP = "JLC0216A"
pcblib.JLC_STACKUPS.setdefault(STACKUP, {
    "thickness": 1.6,
    "finish": "HAL lead-free",
    "layers": [
        ("F.Cu", "copper", 0.030, None, None),
        ("dielectric 1", "core", 1.43, "FR-4 core", 4.5),
        ("B.Cu", "copper", 0.030, None, None),
    ],
})

USB_W, USB_GAP = 0.25, 0.20

CLASSES = {
    "USB": {
        "track_width": USB_W, "diff_pair_width": USB_W, "diff_pair_gap": USB_GAP,
        "diff_pair_via_gap": 0.25, "clearance": 0.15,
        "via_diameter": 0.6, "via_drill": 0.3,
    },
    "POWER": {
        "track_width": 0.4, "clearance": 0.2,
        "via_diameter": 0.8, "via_drill": 0.4,
    },
    "LOOP": {
        "track_width": 0.3, "clearance": 0.25,
        "via_diameter": 0.6, "via_drill": 0.3,
    },
    "GND": {
        "track_width": 0.3, "clearance": 0.15,
        "via_diameter": 0.6, "via_drill": 0.3,
    },
}

PATTERNS = [
    ("USB", "/USB_?"),
    ("POWER", "+5V"), ("POWER", "+3V3"), ("POWER", "+24V"),
    ("POWER", "/VIN_SW"), ("POWER", "/MT_SW"),
    ("LOOP", "/LOOP_V"), ("LOOP", "/LOOP_RTN"), ("LOOP", "/LOOP_C"), ("LOOP", "/LOOP_SNS"),
    ("GND", "GND"),
]

DEFAULT_CLASS = {"track_width": 0.2, "clearance": 0.15, "via_diameter": 0.6, "via_drill": 0.3}

RULES = {
    "min_clearance": 0.127,                 # limit 0.10
    "min_track_width": 0.127,               # limit 0.10
    "min_connection": 0.127,
    "min_via_diameter": 0.5,
    "min_via_annular_width": 0.1,
    "min_through_hole_diameter": 0.3,       # 0.15-0.25 mm holes cost more
    "min_hole_to_hole": 0.25,
    "min_hole_clearance": 0.2,              # J1's own pegs sit at 0.18 from its pads: a library fact, reported separately
    "min_copper_edge_clearance": 0.3,       # routed edge limit 0.2
    "min_silk_clearance": 0.15,
    "min_text_height": 0.8,
    "min_text_thickness": 0.15,
    "min_resolved_spokes": 1,               # 0402 pads beside other nets get one spoke; ample for signal ground
    "solder_mask_to_copper_clearance": 0.0,
    "max_error": 0.005,
    "use_height_for_length_calcs": True,
}

DRU = """(version 1)
# JLCPCB 2-layer, 1 oz -- rules the board constraint table cannot express.
# Generated by setup_fab.py.
# U1 is excluded from the ring rule: its through-hole pads are the module land
# pattern's via-sized thermal holes (0.6 / 0.3 mm), which the via ring rule covers.

(rule "JLC: PTH annular ring, 2-layer 1 oz (0.25 recommended, 0.18 absolute)"
\t(condition "A.Type == 'Pad' && A.Pad_Type == 'Through-hole' && !A.memberOfFootprint('U1')")
\t(constraint annular_width (min 0.18mm)))

(rule "JLC: pad hole to pad hole"
\t(condition "A.Type == 'Pad' && B.Type == 'Pad'")
\t(constraint hole_to_hole (min 0.45mm)))

(rule "JLC: SMD pad to pad, different nets"
\t(condition "A.Type == 'Pad' && B.Type == 'Pad' && A.Pad_Type == 'SMD' && B.Pad_Type == 'SMD' && A.Net != B.Net")
\t(constraint clearance (min 0.15mm)))
"""


def main():
    b = Board(__file__, NAME, size=(W, H))
    b._stale_holes.clear()
    b._stale_zones.clear()
    b.set_netclasses(CLASSES, PATTERNS, RULES)
    pro_path = os.path.join(b.dir, NAME + ".kicad_pro")
    pro = json.load(open(pro_path, encoding="utf-8"))
    for c in pro["net_settings"]["classes"]:
        if c["name"] == "Default":
            c.update(DEFAULT_CLASS)
    json.dump(pro, open(pro_path, "w", encoding="utf-8", newline="\n"), indent=2)
    hit = b.check_netclasses()
    want = {p for _, p in PATTERNS if "?" not in p} | {"/USB_P", "/USB_N"}
    missing = sorted(want - set(hit))
    if missing:
        raise SystemExit("netclass patterns caught nothing for: %s" % missing)
    b.check_diff_pairs(classes=("USB",))
    b.set_stackup(STACKUP)
    dru = os.path.join(b.dir, NAME + ".kicad_dru")
    open(dru, "w", encoding="utf-8", newline="\n").write(DRU)
    say(f"wrote {os.path.basename(dru)}: {DRU.count('(rule ')} JLCPCB rules")


if __name__ == "__main__":
    main()
