M48
; DRILL file KiCad 10.0.6 date 2026-09-20T18:33:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-20T18:33:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X8.61Y-54.67
X14.39Y-54.67
T2
X3.5Y-16.8
X3.5Y-57.5
X36.5Y-16.8
X36.5Y-57.5
M30
